spring.application.name=nextpay

spring.datasource.url=jdbc:h2:mem:nextpaydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

gemini.api.key=${GEMINI_API_KEY:GEMINI_API_KEY}

logging.level.dev.langchain4j=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nextpayaccenture@gmail.com
spring.mail.password=${MAIL_PASSWORD:nzmcbmvyttfuvhit}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com